//
//  Extensions.swift
//  Kalamni
//
//  Created by csuftitan on 2/17/24.
//

import SwiftUI
import Foundation

extension Encodable {
    func asDictionary() -> [String: Any] {
        guard let data = try? JSONEncoder().encode(self) else {
            return [:]
        }
        
        do {
            let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
            return json ?? [:]
        } catch {
            return [:]
        }
    }
}

extension Array {
    func chunked(into size: Int) -> [[Element]] {
        return stride(from: 0, to: count, by: size).map {
            Array(self[$0 ..< Swift.min($0 + size, count)])
        }
    }
}

extension View {
    func Print(_ vars: Any...) -> some View {
        for v in vars { print(v) }
        return EmptyView()
    }
}

extension SoundboardItem {
    static let sampleData: [SoundboardItem] =
    [
        SoundboardItem(id: "0",
                       image: "img/dir",
                       category: "greetings",
                       textEnglish: "Hello",
                       textArabic: "مرحبًا",
                       isFavorite: false),
        
        SoundboardItem(id: "1",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "I",
                       textArabic: "أنا",
                       isFavorite: false),
        
        SoundboardItem(id: "2",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "Want",
                       textArabic: "بدي",
                       isFavorite: false),
        
        SoundboardItem(id: "3",
                       image: "img/dir",
                       category: "Test1",
                       textEnglish: "Water",
                       textArabic: "ماء",
                       isFavorite: false),
        
        SoundboardItem(id: "4",
                       image: "img/dir",
                       category: "Test1",
                       textEnglish: "Food",
                       textArabic: "أكل",
                       isFavorite: false),
        SoundboardItem(id: "5",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "Please",
                       textArabic: "لو سمحت",
                       isFavorite: false),
        
        SoundboardItem(id: "6",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "Thank you",
                       textArabic: "شكرن",
                       isFavorite: false),
        
        SoundboardItem(id: "7",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "Yes",
                       textArabic: "نعم",
                       isFavorite: false),
        
        SoundboardItem(id: "8",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "No",
                       textArabic: "لا",
                       isFavorite: false),
        
        SoundboardItem(id: "9",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "More",
                       textArabic: "أكثر",
                       isFavorite: false),
        
        SoundboardItem(id: "10",
                       image: "img/dir",
                       category: "connecters",
                       textEnglish: "Less",
                       textArabic: "أقل",
                       isFavorite: false),
        
        SoundboardItem(id: "11",
                       image: "img/dir",
                       category: "numbers",
                       textEnglish: "One",
                       textArabic: "وحد",
                       isFavorite: false),
        
        SoundboardItem(id: "12",
                       image: "img/dir",
                       category: "numbers",
                       textEnglish: "Two",
                       textArabic: "إثنان",
                       isFavorite: false),
        
        SoundboardItem(id: "13",
                       image: "img/dir",
                       category: "numbers",
                       textEnglish: "Three",
                       textArabic: "ثلاث",
                       isFavorite: false),
        
        SoundboardItem(id: "14",
                       image: "img/dir",
                       category: "greetings",
                       textEnglish: "Good morning",
                       textArabic: "صباح الخير",
                       isFavorite: false),
        
        SoundboardItem(id: "15",
                       image: "img/dir",
                       category: "Test4",
                       textEnglish: "Good night",
                       textArabic: "تصبح على خير",
                       isFavorite: false),
        
        SoundboardItem(id: "16",
                       image: "img/dir",
                       category: "Test5",
                       textEnglish: "Good bye",
                       textArabic: "مع السلامة",
                       isFavorite: false),
        
        SoundboardItem(id: "0",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "neck",
                       textArabic: "عنق",
                       isFavorite: false),

        SoundboardItem(id: "1",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "chest",
                       textArabic: "صدر",
                       isFavorite: false),

        SoundboardItem(id: "2",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "abdomen",
                       textArabic: "بطن",
                       isFavorite: false),

        SoundboardItem(id: "3",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "head",
                       textArabic: "رأس",
                       isFavorite: false),

        SoundboardItem(id: "4",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "thigh",
                       textArabic: "فخذ",
                       isFavorite: false),

        SoundboardItem(id: "5",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "foot",
                       textArabic: "قدم",
                       isFavorite: false),

        SoundboardItem(id: "6",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "leg",
                       textArabic: "ساق",
                       isFavorite: false),

        SoundboardItem(id: "7",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "shoulder",
                       textArabic: "كتف",
                       isFavorite: false),

        SoundboardItem(id: "8",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "arm",
                       textArabic: "ذراع",
                       isFavorite: false),

        SoundboardItem(id: "9",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "elbow",
                       textArabic: "كوع",
                       isFavorite: false),

        SoundboardItem(id: "10",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "back",
                       textArabic: "ظهر",
                       isFavorite: false),

        SoundboardItem(id: "11",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "wrist",
                       textArabic: "رسغ",
                       isFavorite: false),

        SoundboardItem(id: "12",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "hand",
                       textArabic: "يد",
                       isFavorite: false),

        SoundboardItem(id: "13",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "ankle",
                       textArabic: "كاحل",
                       isFavorite: false),

        SoundboardItem(id: "14",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "armpit",
                       textArabic: "إبط",
                       isFavorite: false),

        SoundboardItem(id: "15",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "hair",
                       textArabic: "شعر",
                       isFavorite: false),

        SoundboardItem(id: "16",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "skin",
                       textArabic: "جلد",
                       isFavorite: false),

        SoundboardItem(id: "17",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "eyebrow",
                       textArabic: "حاجب",
                       isFavorite: false),

        SoundboardItem(id: "18",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "eyelash",
                       textArabic: "رمش",
                       isFavorite: false),

        SoundboardItem(id: "19",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "ear",
                       textArabic: "أذن",
                       isFavorite: false),

        SoundboardItem(id: "20",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "nose",
                       textArabic: "أنف",
                       isFavorite: false),

        SoundboardItem(id: "21",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "lip",
                       textArabic: "شفة",
                       isFavorite: false),

        SoundboardItem(id: "22",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "chin",
                       textArabic: "ذقن",
                       isFavorite: false),

        SoundboardItem(id: "23",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "eye",
                       textArabic: "عين",
                       isFavorite: false),

        SoundboardItem(id: "24",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "cheek",
                       textArabic: "خدّ",
                       isFavorite: false),

        SoundboardItem(id: "25",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "mouth",
                       textArabic: "فم",
                       isFavorite: false),

        SoundboardItem(id: "26",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "jaw",
                       textArabic: "فك",
                       isFavorite: false),

        SoundboardItem(id: "27",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "freckle",
                       textArabic: "نمش",
                       isFavorite: false),

        SoundboardItem(id: "28",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "grandmother",
                       textArabic: "جدة",
                       isFavorite: false),

        SoundboardItem(id: "29",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "grandfather",
                       textArabic: "جد",
                       isFavorite: false),

        SoundboardItem(id: "30",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "mother",
                       textArabic: "أم",
                       isFavorite: false),

        SoundboardItem(id: "31",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "father",
                       textArabic: "أب",
                       isFavorite: false),

        SoundboardItem(id: "32",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "aunt (paternal)",
                       textArabic: "عمة",
                       isFavorite: false),

        SoundboardItem(id: "33",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "uncle (paternal)",
                       textArabic: "عم",
                       isFavorite: false),

        SoundboardItem(id: "34",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "aunt (maternal)",
                       textArabic: "حماة",
                       isFavorite: false),

        SoundboardItem(id: "35",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "uncle (maternal)",
                       textArabic: "حم",
                       isFavorite: false),

        SoundboardItem(id: "36",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "brother",
                       textArabic: "أخ",
                       isFavorite: false),

        SoundboardItem(id: "37",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "sister",
                       textArabic: "أخت",
                       isFavorite: false),

        SoundboardItem(id: "38",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "cousin (paternal)",
                       textArabic: "ابن عم",
                       isFavorite: false),

        SoundboardItem(id: "39",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "cousin (maternal)",
                       textArabic: "ابن حم",
                       isFavorite: false),

        SoundboardItem(id: "40",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "husband",
                       textArabic: "زوج",
                       isFavorite: false),

        SoundboardItem(id: "41",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "wife",
                       textArabic: "زوجة",
                       isFavorite: false),

        SoundboardItem(id: "42",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "daughter",
                       textArabic: "بنت",
                       isFavorite: false),

        SoundboardItem(id: "43",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "son",
                       textArabic: "ابن",
                       isFavorite: false),

        SoundboardItem(id: "44",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "granddaughter",
                       textArabic: "حفيدة",
                       isFavorite: false),

        SoundboardItem(id: "45",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "grandson",
                       textArabic: "حفيد",
                       isFavorite: false),

        SoundboardItem(id: "46",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "baby",
                       textArabic: "رضيع",
                       isFavorite: false),

        SoundboardItem(id: "47",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "child",
                       textArabic: "طفل",
                       isFavorite: false),

        SoundboardItem(id: "48",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "boy",
                       textArabic: "ولد",
                       isFavorite: false),

        SoundboardItem(id: "49",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "girl",
                       textArabic: "بنت",
                       isFavorite: false),

        SoundboardItem(id: "50",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "teenager",
                       textArabic: "مراهق",
                       isFavorite: false),

        SoundboardItem(id: "51",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "adult",
                       textArabic: "بالغ",
                       isFavorite: false),

        SoundboardItem(id: "52",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "man",
                       textArabic: "رجل",
                       isFavorite: false),

        SoundboardItem(id: "53",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "woman",
                       textArabic: "امرأة",
                       isFavorite: false),

        SoundboardItem(id: "54",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "happy",
                       textArabic: "سعيد",
                       isFavorite: false),

        SoundboardItem(id: "55",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "sad",
                       textArabic: "حزين",
                       isFavorite: false),

        SoundboardItem(id: "56",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "excited",
                       textArabic: "متحمس",
                       isFavorite: false),

        SoundboardItem(id: "57",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "bored",
                       textArabic: "ممل",
                       isFavorite: false),

        SoundboardItem(id: "58",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "surprised",
                       textArabic: "مندهش",
                       isFavorite: false),

        SoundboardItem(id: "59",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "scared",
                       textArabic: "مقدس",
                       isFavorite: false),

        SoundboardItem(id: "60",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "angry",
                       textArabic: "غاضب",
                       isFavorite: false),

        SoundboardItem(id: "61",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "confused",
                       textArabic: "مرتبك",
                       isFavorite: false),

        SoundboardItem(id: "62",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "worried",
                       textArabic: "قلق",
                       isFavorite: false),

        SoundboardItem(id: "63",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "nervous",
                       textArabic: "عصبي",
                       isFavorite: false),

        SoundboardItem(id: "64",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "laugh",
                       textArabic: "يضحك",
                       isFavorite: false),

        SoundboardItem(id: "65",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "shout",
                       textArabic: "يصيح",
                       isFavorite: false),

        SoundboardItem(id: "66",
                       image: "img/dir",
                       category: "people",
                       textEnglish: "cry",
                       textArabic: "يبكي",
                       isFavorite: false),

        SoundboardItem(id: "67",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "cereal",
                       textArabic: "حبوب الفطور",
                       isFavorite: false),

        SoundboardItem(id: "68",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "vegetables",
                       textArabic: "خضراوات",
                       isFavorite: false),

        SoundboardItem(id: "69",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "fruit",
                       textArabic: "فاكهة",
                       isFavorite: false),

        SoundboardItem(id: "70",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "fish",
                       textArabic: "سمك",
                       isFavorite: false),

        SoundboardItem(id: "71",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "drink",
                       textArabic: "مشروبات",
                       isFavorite: false),

        SoundboardItem(id: "72",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "candy",
                       textArabic: "حلويات",
                       isFavorite: false),

        SoundboardItem(id: "73",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "chocolate",
                       textArabic: "شوكولاتة",
                       isFavorite: false),

        SoundboardItem(id: "74",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "chocolate bar",
                       textArabic: "قطعة شوكولاتة",
                       isFavorite: false),

        SoundboardItem(id: "75",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "lollipop",
                       textArabic: "مصاصة",
                       isFavorite: false),

        SoundboardItem(id: "76",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "mint",
                       textArabic: "نعناع",
                       isFavorite: false),

        SoundboardItem(id: "77",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "marshmallow",
                       textArabic: "حلوع الخطمي",
                       isFavorite: false),

        SoundboardItem(id: "78",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "gum",
                       textArabic: "لبان",
                       isFavorite: false),

        SoundboardItem(id: "79",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "licorice",
                       textArabic: "عرق سوس",
                       isFavorite: false),

        SoundboardItem(id: "80",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "cookie",
                       textArabic: "بسكوت",
                       isFavorite: false),

        SoundboardItem(id: "81",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "dark chocolate",
                       textArabic: "شوكولاتة سادة",
                       isFavorite: false),

        SoundboardItem(id: "82",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "milk chocolate",
                       textArabic: "شوكولاتة بالحليب",
                       isFavorite: false),

        SoundboardItem(id: "83",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "white chocolate",
                       textArabic: "شوكولاتة بيضاء",
                       isFavorite: false),

        SoundboardItem(id: "84",
                       image: "img/dir",
                       category: "shopping",
                       textEnglish: "caramel",
                       textArabic: "كرملة",
                       isFavorite: false),

        SoundboardItem(id: "85",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "headache",
                       textArabic: "صداع",
                       isFavorite: false),

        SoundboardItem(id: "86",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "cough",
                       textArabic: "كحة",
                       isFavorite: false),

        SoundboardItem(id: "87",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "fever",
                       textArabic: "حمی",
                       isFavorite: false),

        SoundboardItem(id: "88",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "asthma",
                       textArabic: "ربو",
                       isFavorite: false),

        SoundboardItem(id: "89",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "cramps",
                       textArabic: "تقلصات",
                       isFavorite: false),

        SoundboardItem(id: "90",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "nausea",
                       textArabic: "غثيان",
                       isFavorite: false),

        SoundboardItem(id: "91",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "cold",
                       textArabic: "برد",
                       isFavorite: false),

        SoundboardItem(id: "92",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "rash",
                       textArabic: "طفح جلدي",
                       isFavorite: false),

        SoundboardItem(id: "93",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "chicken pox",
                       textArabic: "جدري الماء",
                       isFavorite: false),

        SoundboardItem(id: "94",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "eczema",
                       textArabic: "اكزيما",
                       isFavorite: false),

        SoundboardItem(id: "95",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "vomit",
                       textArabic: "يتقيا",
                       isFavorite: false),

        SoundboardItem(id: "96",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "diarrhea",
                       textArabic: "إسهال",
                       isFavorite: false),

        SoundboardItem(id: "97",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "allergy",
                       textArabic: "حساسية",
                       isFavorite: false),

        SoundboardItem(id: "98",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "doctor",
                       textArabic: "طبيب",
                       isFavorite: false),

        SoundboardItem(id: "99",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "nurse",
                       textArabic: "ممرضة",
                       isFavorite: false),

        SoundboardItem(id: "100",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "appointment",
                       textArabic: "موعد",
                       isFavorite: false),

        SoundboardItem(id: "101",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "medical exam",
                       textArabic: "فحص طبي",
                       isFavorite: false),

        SoundboardItem(id: "102",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "cut",
                       textArabic: "جرح",
                       isFavorite: false),

        SoundboardItem(id: "103",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "sunburn",
                       textArabic: "لفح",
                       isFavorite: false),

        SoundboardItem(id: "104",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "burn",
                       textArabic: "حرق",
                       isFavorite: false),

        SoundboardItem(id: "105",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "bruise",
                       textArabic: "كدمة",
                       isFavorite: false),

        SoundboardItem(id: "106",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "accident",
                       textArabic: "حادث",
                       isFavorite: false),

        SoundboardItem(id: "107",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "blister",
                       textArabic: "بثرة",
                       isFavorite: false),

        SoundboardItem(id: "108",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "choke",
                       textArabic: "يختنق",
                       isFavorite: false),

        SoundboardItem(id: "109",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "bandage",
                       textArabic: "ضمادة",
                       isFavorite: false),

        SoundboardItem(id: "110",
                       image: "img/dir",
                       category: "health",
                       textEnglish: "tweezer",
                       textArabic: "ملقط",
                       isFavorite: false),


    ]
}

extension SoundboardItem {
    static let sampleDataOne: [SoundboardItem] = [
        SoundboardItem(id: "0",
                       image: "img/dir",
                       category: "Test1",
                       textEnglish: "Hello",
                       textArabic: "مرحبًا",
                       isFavorite: false),
    ]
}

extension SoundboardItem {
    static let sampleDataEmpty: [SoundboardItem] = []
}

extension SoundboardItem {
    static let sampleMessage: [SoundboardItem] = [
        SoundboardItem(id: "0",
                       image: "img/dir",
                       category: "Test1",
                       textEnglish: "Hello",
                       textArabic: "مرحبًا",
                       isFavorite: false),
        
        SoundboardItem(id: "1",
                       image: "img/dir",
                       category: "Test5",
                       textEnglish: "Good bye",
                       textArabic: "مع السلامة",
                       isFavorite: false),
    ]
}
